steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/upgraded-spoon:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/upgraded-spoon:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'upgraded-spoon'
    - '--image'
    - 'gcr.io/$PROJECT_ID/upgraded-spoon:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'BUCKET_NAME=${_BUCKET_NAME}'

images:
  - 'gcr.io/$PROJECT_ID/upgraded-spoon:$COMMIT_SHA'

substitutions:
  _BUCKET_NAME: 'upgraded-spoon-files' # Default bucket name

options:
  logging: CLOUD_LOGGING_ONLY
